spring:
  devtools:
    add-properties: 'true'
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/petals?zeroDateTimeBehavior=convertToNull
    password: root
  application:
    name: PetalsPG
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: 'true'
server:
  port: '8080'
